[package]
name = "abc150"
version = "0.1.0"
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "*"
memoise = "*"
num = "0.4.0"

[profile.release]
lto = true
panic = 'abort'
