[package]
name = "pakencamp-2019-day3"
version = "0.1.0"
edition = "2018"

# dependencies added to new project
[dependencies]
memoise = "0.3.2"
proconio = "*"

[profile.release]
lto = true
panic = 'abort'
