[package]
name = "arc033"
version = "0.1.0"
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "*"
memoise = "*"
ndarray = "*"
nalgebra = "*"
superslice = "1.0.0"

[profile.release]
lto = true
panic = 'abort'
